name: build Koa project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build pkg
        working-directory: ./koa_project
        run: |
          npm install
          npm install -g pkg
          pkg app.js
      - uses: actions/upload-artifact@v2
        with:
          name: app-macos
          path: ./koa_project/app-macos
