name: build Koa project
on: [push]
jobs:
	Explore-GitHub-Actions:
    	runs-on: macos-11
		steps:
			- run: ls -al
			- run: cd build_on_github_actions
			- run: cd koa_project
			- run: npm install -g pkg
			- run: pkg app.js
      

	
