name: build Koa project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build pkg
        working-directory: ./koa_project
        run: |
          npm install
          npm install -g pkg
          npm run prebuild
      - name: build docker image
        working-directory: ./koa_project
        run: |
          docker build -t release/koa_project:test .
          docker save release/koa_project:test > koa_project.tar
          ls
      - uses: actions/upload-artifact@v2
        with:
          name: Executable file for Linux
          path: ./koa_project/app
      - uses: actions/upload-artifact@v2
        with:
          name: Image file for docker
          path: ./koa_project/koa_project.tar
